spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        health-check-url: http://127.0.0.1/actuator/heath
  application:
    name: consul-client
server:
  port: 2002